#!/usr/bin/env bash
set -ex
mkdir -p ../results/chapter{02,03,04,05,06,07,08,09,10,11,12,13}
# Chapter 2:
cd ./chapter02
Rscript "GerberGreenBook_Chapter2_HowToRandomize_7treat2.R"
Rscript "GerberGreenBook_Chapter2_Simulation_7_treat_2_Table_2_1.R"

# Chapter 3:
cd ../chapter03
Rscript "Arceneaux_AAAPSSsubset_2005_CodeforCh3.R"
Rscript "GerberGreenBook_Chapter3_Figure_1.R"
Rscript "GerberGreenBook_Chapter3_RIandTTest_Box_3_7.R"
